### ISSUE TITLE
Перенос калькулятора в настройки сетки

### ISSUE THREAD

**Issue by VT-1** [g992/SBX#1]
В данный момент неудобно пользоваться калькулятором - при изменении сетки нужно перемещаться в другое меню для просмотра получившейся сетки, а было бы очевидней чтобы готовая сетка отображалась сразу под её настройками, и пересчитывалась сама после внесения изменений в настройки.
![Снимок экрана 2021-09-05 122339](https://user-images.githubusercontent.com/90132687/132121961-e88f94f1-e57e-4caa-a317-b40b1229ea2d.jpg)

**Comment by Brakomes** [comment]
Абсолютно поддерживаю! Эта мысль сразу приходит в голову даже новичкам, когда они сталкиваются с этой настройкой.

**Comment by g992** [comment]
Расчет сетки перенесен в вкладку "Сетка", авторасчет не добавлен т.к.  это достаточно ресурсозатратная функция и в случае опечатки бот может намертво зависнуть. Выбор пары по прежнему требуется, т.к. от него многое зависит.
![image](https://user-images.githubusercontent.com/48438685/132809036-7430ef4f-30c5-45e7-9e35-646522c009b9.png)
