### ISSUE TITLE
Добавить обратную связь к кнопке "Применить"

### ISSUE THREAD

**Issue by VT-1** [g992/SBX#6]
Сейчас при нажатии кнопки не происходит ничего, и непонятно, есть ли эффект или бот вообще "висит".
Оптимально было бы выводить в правой колонке сообщение о том, что "Изменения успешно применены" или "Будут применены только *при соблюдении таких-то условий*".

**Comment by g992** [comment]
Добавил сообщение в боковом логе.
![image](https://user-images.githubusercontent.com/48438685/132809424-81ac8d51-48ea-455b-9bb7-08fa2672777b.png)
